"""add song field

Revision ID: 2a860a6a6d9c
Revises: 1555e1849b71
Create Date: 2026-05-18 18:19:17.147159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a860a6a6d9c'
down_revision: Union[str, Sequence[str], None] = '1555e1849b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('songs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('songs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'updated_at')
    op.drop_column('songs', 'created_at')
    op.drop_column('songs', 'category')
    # ### end Alembic commands ###
