"""create user table

Revision ID: 30fe154d04aa
Revises: bbb2ebb893ee
Create Date: 2026-04-16 14:04:42.466006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fe154d04aa'
down_revision: Union[str, Sequence[str], None] = 'bbb2ebb893ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_useres_email'), 'useres', ['email'], unique=True)
    op.create_index(op.f('ix_useres_id'), 'useres', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useres_id'), table_name='useres')
    op.drop_index(op.f('ix_useres_email'), table_name='useres')
    op.drop_table('useres')
    # ### end Alembic commands ###
