"""set lyrics not null

Revision ID: 96a3a243dc12
Revises: 2e33752a0c3c
Create Date: 2026-09-19 12:04:54.639356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a3a243dc12'
down_revision: Union[str, Sequence[str], None] = '2e33752a0c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'lyrics',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'lyrics',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
