"""add chordpro to songs

Revision ID: d49c1fed2588
Revises: 6902f251c9e5
Create Date: 2026-09-19 12:55:49.616392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49c1fed2588'
down_revision: Union[str, Sequence[str], None] = '6902f251c9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('chordpro', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'chordpro')
    # ### end Alembic commands ###
