"""add ministry rbac

Revision ID: fbba793089e2
Revises: 79d0f253f522
Create Date: 2026-09-19 13:53:21.394057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbba793089e2"
down_revision: Union[str, Sequence[str], None] = "79d0f253f522"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE users SET role = 'MEMBER' WHERE role = 'USER'")
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(),
        type_=sa.String(length=6),
        existing_nullable=False,
        server_default="MEMBER",
    )
    op.create_check_constraint(
        "user_role",
        "users",
        "role IN ('ADMIN', 'LEADER', 'MEMBER')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ministries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_ministries_id"), "ministries", ["id"], unique=False)
    op.create_table(
        "ministry_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ministry_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "LEADER",
                "MEMBER",
                name="ministry_role",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="MEMBER",
            nullable=False,
        ),
        sa.Column("instrument", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ministry_id"], ["ministries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ministry_id", "user_id", name="uq_ministry_members_ministry_user"
        ),
    )
    op.create_index(
        op.f("ix_ministry_members_id"), "ministry_members", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ministry_members_ministry_id"),
        "ministry_members",
        ["ministry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ministry_members_user_id"),
        "ministry_members",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ministry_members_user_id"), table_name="ministry_members")
    op.drop_index(
        op.f("ix_ministry_members_ministry_id"), table_name="ministry_members"
    )
    op.drop_index(op.f("ix_ministry_members_id"), table_name="ministry_members")
    op.drop_table("ministry_members")
    op.drop_index(op.f("ix_ministries_id"), table_name="ministries")
    op.drop_table("ministries")
    # ### end Alembic commands ###

    op.drop_constraint("user_role", "users", type_="check")
    op.execute("UPDATE users SET role = 'USER' WHERE role IN ('MEMBER', 'LEADER')")
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(length=6),
        type_=sa.String(),
        existing_nullable=False,
        server_default=None,
    )
